// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptLicense():Promise<void>;

export function EnsureSharedSetup():Promise<main.NodeActionResult>;

export function GetActionMessage():Promise<string>;

export function CheckReleaseUpdate():Promise<main.ReleaseUpdateView>;

export function GetBootstrap():Promise<main.BootstrapView>;

export function GetDashboard():Promise<main.DashboardView>;

export function GetInstallDir():Promise<string>;

export function GetNodeLogs():Promise<Array<string>>;

export function GetRecommendedLinks():Promise<Record<string, string>>;

export function GetRegisterStatus():Promise<main.RegisterStatusView>;

export function GetWalletStatus():Promise<main.WalletStatusView>;

export function IsNodeRunning():Promise<boolean>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenInstallFolder():Promise<void>;

export function RegisterNode(arg1:string):Promise<main.RegisterNodeResult>;

export function RemoveNode(arg1:string):Promise<main.UnstakeNodeResult>;

export function RepairInstall():Promise<main.InstallResult>;

export function RunInstall():Promise<main.InstallResult>;

export function SetInstallDir(arg1:string):Promise<void>;

export function SetInstallScope(arg1:string):Promise<void>;

export function SetWalletAddress(arg1:string):Promise<main.BrowserSignInResult>;

export function SignInWithBrowser():Promise<main.BrowserSignInResult>;

export function SignOut():Promise<void>;

export function StartNode(arg1:string):Promise<main.NodeActionResult>;

export function StopNode(arg1:string):Promise<main.NodeActionResult>;

export function UnstakeNode(arg1:string):Promise<main.UnstakeNodeResult>;
