// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptLicense() {
  return window['go']['main']['App']['AcceptLicense']();
}

export function CheckReleaseUpdate() {
  return window['go']['main']['App']['CheckReleaseUpdate']();
}

export function EnsureSharedSetup() {
  return window['go']['main']['App']['EnsureSharedSetup']();
}

export function GetActionMessage() {
  return window['go']['main']['App']['GetActionMessage']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetInstallDir() {
  return window['go']['main']['App']['GetInstallDir']();
}

export function GetNodeLogs() {
  return window['go']['main']['App']['GetNodeLogs']();
}

export function GetRecommendedLinks() {
  return window['go']['main']['App']['GetRecommendedLinks']();
}

export function GetRegisterStatus() {
  return window['go']['main']['App']['GetRegisterStatus']();
}

export function GetWalletStatus() {
  return window['go']['main']['App']['GetWalletStatus']();
}

export function IsNodeRunning() {
  return window['go']['main']['App']['IsNodeRunning']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenInstallFolder() {
  return window['go']['main']['App']['OpenInstallFolder']();
}

export function RegisterNode(arg1) {
  return window['go']['main']['App']['RegisterNode'](arg1);
}

export function RemoveNode(arg1) {
  return window['go']['main']['App']['RemoveNode'](arg1);
}

export function RepairInstall() {
  return window['go']['main']['App']['RepairInstall']();
}

export function RunInstall() {
  return window['go']['main']['App']['RunInstall']();
}

export function SetInstallDir(arg1) {
  return window['go']['main']['App']['SetInstallDir'](arg1);
}

export function SetInstallScope(arg1) {
  return window['go']['main']['App']['SetInstallScope'](arg1);
}

export function SetWalletAddress(arg1) {
  return window['go']['main']['App']['SetWalletAddress'](arg1);
}

export function SignInWithBrowser() {
  return window['go']['main']['App']['SignInWithBrowser']();
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StartNode(arg1) {
  return window['go']['main']['App']['StartNode'](arg1);
}

export function StopNode(arg1) {
  return window['go']['main']['App']['StopNode'](arg1);
}

export function UnstakeNode(arg1) {
  return window['go']['main']['App']['UnstakeNode'](arg1);
}
